name: openim_live
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil:
  get: 4.6.6
  livekit_client: ^2.0.0
  flutter_background: 1.3.0+1
  eva_icons_flutter: 3.1.0
  flutter_svg: 2.0.9
  rxdart:
  lottie:
  synchronized:
  wakelock_plus: ^1.1.3
  sprintf: 7.0.0
  animate_do: 3.0.2
  common_utils: 2.1.0
  uuid:
  device_info_plus:
  openim_common:
    path: ../openim_common
  flutter_openim_sdk:
    path: ../../open-im-sdk

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
    
dependency_overrides:
  flutter_webrtc: 0.12.10

flutter:
  uses-material-design: true
